#!/bin/sh

if [ "$1" == "web" ]; then
	echo "making for web...";
	echo \#define PLATFORM_WEB >| src/platform.h && make web
elif [ "$1" == "desktop" ]; then
	echo "building for desktop...";
	echo  \/\/ \#define PLATFORM_WEB >| src/platform.h && make
elif [ "$1" == "clean" ]; then
	echo "cleaning old stuff...";
	make clean;
else
	./build web && ./build desktop
fi

